# Generated by Django 4.2.15 on 2024-08-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_historicalorderitem_item_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='is_moved',
            field=models.BooleanField(default=False, verbose_name='Birləşmiş sifariş'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_moved',
            field=models.BooleanField(default=False, verbose_name='Birləşmiş sifariş'),
        ),
    ]
